### ISSUE TITLE
[Shared Server] Multiple fixes

### ISSUE THREAD

**Issue by juanmzaragoza** [juanmzaragoza/tp-taller2#62]
@Erik I attach you some bugs that I finded

* id hard-coded: we haved talk that we take the user id from user fb
* in case that the mandatory fields like id, username, password they are empty, you have tu return a 400 response
* Add version to endpoint. For example: http://localhost:8081/api/v1/user/1
* Catch UnauthorizedError - The method /user/:id is returning a html response instead a json
* docker angular is not working

**Comment by juanmzaragoza** [comment]
You have to validate that user id is not duplicated in the databases

**Comment by erikschmoll** [comment]
@juanmzaragoza : sobre:Add version to endpoint. For example: http://localhost:8081/api/v1/user/1 dijeron que se tiene que pasar en el response como metadata
