### ISSUE TITLE
Shared Server :: Persistir datos en postgred

### ISSUE THREAD

**Issue by erikschmoll** [juanmzaragoza/tp-taller2#84]
Issue técnico, se necesita crear el servicio que guarda en base de datos y eliminar el StorageService

**Comment by kaoruheanna** [comment]
A que te referis? porque ya se estan guardando cosas en DB

**Comment by erikschmoll** [comment]
Revisa el archivo ~/services/server.service.js vas a notar que usa:
const StorageServ       = require('./storage.service')
Esto se debe cambiar por el servicio que guarda en la base de datos.
